Cat/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :cats, except: :destroy
  resources :cat_rental_requests, only: [:new, :create] do
    member do
      post :approve
      post :deny
    end
  end

  resources :users, only:[:new, :create, :show]
  resource :session, only:[:new, :create, :destroy]


  root to: redirect('/cats')
end

Cat/app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :bigint(8)        not null, primary key
#  username        :string           not null
#  password_digest :string           not null
#  session_token   :string           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class User < ApplicationRecord
  validates :username, presence: true, uniqueness: true
  validates :password_digest, presence: { message: 'Password can\'t be blank'}
  validates :session_token, presence: true, uniqueness: true
  validates :password, length: { minimum: 6, allow_nil: true }

  # before_validation :ensure_session_token

  after_initialize :ensure_session_token

  def ensure_session_token
    self.session_token ||= SecureRandom.urlsafe_base64
  end

  def reset_session_token!
    self.session_token = SecureRandom.urlsafe_base64
    self.save!
    self.session_token
  end

  attr_reader :password

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def self.find_by_credentials(user_name, password)
    user = User.find_by(username: user_name)

    if user && user.is_password?(password)
      user
    else
      nil
    end
  end


end

Cat/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_log_out, only: [:new]

  def show
    @user = User.find(params[:id])
    render (:show)
  end

  def new
    @user = User.new
    render :new
  end

  def create
    @user = User.new(user_params)

    if @user.save!
      login(@user)
      redirect_to user_url(@user)
    else
      flash[:errors] = @user.errors.full_messages
      redirect_to new_user_url
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :password)
  end
end

Cat/app/views/users/_form.html.erb
  <% if type == :new %>
  <% action_url = users_url%>
  <% button_text = "Create User!"%>

  <% elsif type == :login %>
  <% action_url = session_url %>
  <% button_text = "Log In User!"%>

  <% else %>
  <% action_url = user_url(template_user)%>
  <% button_text = "Update User!"%>
  <% end  %>


  <form action="<%=action_url%>" method="post">
    <input name="authenticity_token" type="hidden" value="<%= form_authenticity_token %>" />

    <% if type == :edit%>
    <input type="hidden" name="_method" value="patch">
    <% end %>

    <label for="username">
      Username:
      <input type="text" name="user[username]" value="<%=template_user.username%>">
    </label>
    <br>
    <label for="password">
      Password:
      <input type="password" name="user[password]">
      </input>
    </label>
    <br>


    <input type="submit" value="<%= button_text %>">
  </form>

Cat/app/views/users/edit.html.erb
<h1>Edit</h1>
<%= render 'form', template_user: @user, type: :edit%>

Cat/app/views/users/index.html.erb
<h1>hi</h1>

Cat/app/views/users/new.html.erb
<h1>Sign Up</h1>
<%= render 'form', template_user: @user, type: :new%>

Cat/app/views/users/show.html.erb
<h1>hi</h1>